# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f99ad4e93c58e3e7f8696321bee9d4f88f16aaa1b95263596dca29073d9ed90fd7f9310d90ca7d17fe7b7263869ab1477e6ec60076c647b5b9d73d78e80521

test:
  secret_key_base: 4e1d9b436432c3206af46a8ca4401e18f3f02fe9efcc2f1eaec8719eab967191fe185de613f32d044d8073d94d07da4db4d6f1ef3172ebea49cd373c573d9454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
